apiVersion: v1
kind: Service
metadata:
  name: bookcrossingcust
spec:
  type: ClusterIP
  ports:
    - name: rest-port-c
      port: 8002
      targetPort: 8002
    - name: grpc-port-c
      port: 8012
      targetPort: 8012
  selector:
    app: bookcrossingcust