apiVersion: v1
kind: Service
metadata:
  name: bookcrossingmediator
spec:
  type: ClusterIP
  ports:
    - name: rest
      port: 8081
      targetPort: 8081
    - name: grpc
      port: 8091
      targetPort: 8091
  selector:
    app: bookcrossingmediator