apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookcrossingmediator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookcrossingmediator
  template:
    metadata:
      labels:
        app: bookcrossingmediator
    spec:
      containers:
        - image: mediator:0.0.1-SNAPSHOT
          name: bookcrossingmediator
          imagePullPolicy: Never
          resources:
            limits:
              memory: 1Gi
            requests:
              memory: 512Mi
          ports:
            - containerPort: 8081
              name: rest-port-m
            - containerPort: 8091
              name: grpc-port-m