apiVersion: v1
kind: Service
metadata:
  name: bookcrossingorder
spec:
  type: ClusterIP
  ports:
    - name: rest-port-o
      port: 8003
      targetPort: 8003
    - name: grpc-port-o
      port: 8013
      targetPort: 8013
  selector:
    app: bookcrossingorder