apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookcrossingorder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookcrossingorder
  template:
    metadata:
      labels:
        app: bookcrossingorder
    spec:
      containers:
        - image: bookorder:0.0.1-SNAPSHOT
          name: bookcrossingorder
          imagePullPolicy: Never
          resources:
            limits:
              memory: 1Gi
            requests:
              memory: 512Mi
          ports:
            - containerPort: 8003
              name: rest-port-o
            - containerPort: 8013
              name: grpc-port-o