apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookcrossingbook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookcrossingbook
  template:
    metadata:
      labels:
        app: bookcrossingbook
    spec:
      hostNetwork: true
      containers:
        - image: book:0.0.1-SNAPSHOT
          name: bookcrossingbook
          imagePullPolicy: Never
          ports:
            - containerPort: 8001
              name: rest-port
            - containerPort: 8011
              name: grpc-port