apiVersion: v1
kind: Service
metadata:
  name: bookcrossingbook
spec:
  type: ClusterIP
  ports:
    - name: rest-port
      port: 8001
      targetPort: 8001
    - name: grpc-port
      port: 8011
      targetPort: 8011
  selector:
    app: bookcrossingbook