apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookcrossingbox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookcrossingbox
  template:
    metadata:
      labels:
        app: bookcrossingbox
    spec:
      containers:
        - image: box:0.0.1-SNAPSHOT
          name: bookcrossingbox
          imagePullPolicy: Never
          resources:
            limits:
              memory: 1Gi
            requests:
              memory: 512Mi
          ports:
            - containerPort: 8004
              name: rest-port-b
            - containerPort: 8014
              name: grpc-port-b